"""initial migration

Revision ID: 356a7dbddd3b
Revises: 
Create Date: 2025-05-31 19:07:38.952900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '356a7dbddd3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), "teaching"):
        op.create_table('teaching',
        sa.Column('tno', sa.String(length=7), nullable=False),
        sa.Column('cno', sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(['cno'], ['course.cno'], ),
        sa.ForeignKeyConstraint(['tno'], ['t.tno'], ),
        sa.PrimaryKeyConstraint('tno', 'cno')
        )
    '''with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cno', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('cname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ccredit', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('cpno', sa.String(length=6), nullable=True))
        batch_op.drop_constraint(batch_op.f('course_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('course_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['cpno'], ['cno'])
        batch_op.drop_column('Cpno')
        batch_op.drop_column('Ccredit')
        batch_op.drop_column('Tno')
        batch_op.drop_column('Cname')
        batch_op.drop_column('Cno')
'''
    with op.batch_alter_table('sc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sno', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('cno', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('grade', sa.SmallInteger(), nullable=True))
        batch_op.drop_constraint(batch_op.f('sc_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sc_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['cno'], ['cno'])
        batch_op.create_foreign_key(None, 'student', ['sno'], ['sno'])
        batch_op.drop_column('Grade')
        batch_op.drop_column('Sno')
        batch_op.drop_column('Cno')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('schedule_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['cno'], ['cno'])
        batch_op.create_foreign_key(None, 't', ['tno'], ['tno'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sno', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('sname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ssex', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('sage', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('sdept', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('SID'))
        batch_op.drop_column('Sno')
        batch_op.drop_column('Sname')
        batch_op.drop_column('Ssex')
        batch_op.drop_column('Sage')
        batch_op.drop_column('SID')
        batch_op.drop_column('Sdept')

    with op.batch_alter_table('t', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tno', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('tname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=20), nullable=True))
        batch_op.drop_column('Tname')
        batch_op.drop_column('Title')
        batch_op.drop_column('Tno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Tno', mysql.CHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('Title', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Tname', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('tname')
        batch_op.drop_column('tno')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sdept', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('SID', mysql.CHAR(length=18), nullable=True))
        batch_op.add_column(sa.Column('Sage', mysql.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ssex', mysql.CHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('Sname', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('Sno', mysql.CHAR(length=10), nullable=False))
        batch_op.create_index(batch_op.f('SID'), ['SID'], unique=True)
        batch_op.drop_column('sdept')
        batch_op.drop_column('sage')
        batch_op.drop_column('ssex')
        batch_op.drop_column('sname')
        batch_op.drop_column('sno')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_ibfk_1'), 'course', ['cno'], ['Cno'])
        batch_op.create_foreign_key(batch_op.f('schedule_ibfk_2'), 't', ['tno'], ['Tno'])

    with op.batch_alter_table('sc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cno', mysql.CHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('Sno', mysql.CHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('Grade', mysql.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sc_ibfk_2'), 'course', ['Cno'], ['Cno'])
        batch_op.create_foreign_key(batch_op.f('sc_ibfk_1'), 'student', ['Sno'], ['Sno'])
        batch_op.drop_column('grade')
        batch_op.drop_column('cno')
        batch_op.drop_column('sno')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cno', mysql.CHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('Cname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('Tno', mysql.CHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('Ccredit', mysql.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Cpno', mysql.CHAR(length=8), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_ibfk_2'), 't', ['Tno'], ['Tno'])
        batch_op.create_foreign_key(batch_op.f('course_ibfk_1'), 'course', ['Cpno'], ['Cno'])
        batch_op.drop_column('cpno')
        batch_op.drop_column('ccredit')
        batch_op.drop_column('cname')
        batch_op.drop_column('cno')

    op.drop_table('teaching')
    # ### end Alembic commands ###
